-- Keys quizzes, materials and roadmap topics off the curriculum instead of topic titles.
--
-- `topic_key` was a free-text string that had to be typed identically in two places for a
-- quiz to find the student studying it. `curriculum_ref` is a slug path into the tree in
-- src/lib/curriculum — `pathology/general-pathology` or `anatomy/upper-limb/wrist-and-hand`
-- — and matching is by branch, so content filed against a section reaches every topic under
-- it. See docs/CURRICULUM.md.

ALTER TABLE "roadmap_topics" ADD COLUMN "curriculum_ref" varchar(200);--> statement-breakpoint
ALTER TABLE "quizzes" ADD COLUMN "curriculum_ref" varchar(200);--> statement-breakpoint
ALTER TABLE "materials" ADD COLUMN "curriculum_ref" varchar(200);--> statement-breakpoint

-- Existing roadmaps were built from templates, and a template week now knows where it sits
-- in the curriculum. Matching on (subject, week title) is exact rather than fuzzy: both
-- sides come from the same template definitions.
UPDATE "roadmap_topics" AS rt
SET "curriculum_ref" = m.ref
FROM (VALUES
  ('anaesthesiology', 'Airway', 'anaesthesiology/airway-and-general-anaesthesia/airway'),
  ('anaesthesiology', 'Critical Care', 'anaesthesiology/resuscitation-and-critical-care/critical-care'),
  ('anaesthesiology', 'General Anaesthesia', 'anaesthesiology/airway-and-general-anaesthesia/general-anaesthesia'),
  ('anaesthesiology', 'Life Support', 'anaesthesiology/resuscitation-and-critical-care/life-support'),
  ('anaesthesiology', 'Local', 'anaesthesiology/regional-and-local-anaesthesia/local'),
  ('anaesthesiology', 'Monitoring', 'anaesthesiology/monitoring-and-perioperative-care/monitoring'),
  ('anaesthesiology', 'Postoperative', 'anaesthesiology/monitoring-and-perioperative-care/postoperative'),
  ('anaesthesiology', 'Preanaesthetic Assessment', 'anaesthesiology/preoperative-and-basic-principles/preanaesthetic-assessment'),
  ('anaesthesiology', 'Regional', 'anaesthesiology/regional-and-local-anaesthesia/regional'),
  ('anaesthesiology', 'Relevant Pharmacology', 'anaesthesiology/preoperative-and-basic-principles/relevant-pharmacology'),
  ('anatomy', 'Ankle & Foot', 'anatomy/lower-limb/ankle-and-foot'),
  ('anatomy', 'Anterior Abdominal Wall', 'anatomy/abdomen-and-pelvis/anterior-abdominal-wall'),
  ('anatomy', 'Arm, Forearm & Hand', 'anatomy/upper-limb'),
  ('anatomy', 'Back & Scapular Region', 'anatomy/upper-limb/back-and-scapular-region'),
  ('anatomy', 'Blood Supply of Brain', 'anatomy/neuroanatomy/blood-supply-of-brain'),
  ('anatomy', 'Brainstem', 'anatomy/neuroanatomy/brainstem'),
  ('anatomy', 'Cerebellum', 'anatomy/neuroanatomy/cerebellum'),
  ('anatomy', 'Cerebrum', 'anatomy/neuroanatomy/cerebrum'),
  ('anatomy', 'Cranial Nerves', 'anatomy/head-and-neck/cranial-nerves'),
  ('anatomy', 'Diencephalon', 'anatomy/neuroanatomy/diencephalon'),
  ('anatomy', 'Ear', 'anatomy/head-and-neck/ear'),
  ('anatomy', 'Embryology & Histology', 'anatomy/histology-genetics-and-applied-anatomy'),
  ('anatomy', 'Face & Scalp', 'anatomy/head-and-neck/face-and-scalp'),
  ('anatomy', 'Forearm & Elbow', 'anatomy/upper-limb/forearm-and-elbow'),
  ('anatomy', 'Gastrointestinal Viscera', 'anatomy/abdomen-and-pelvis/gastrointestinal-viscera'),
  ('anatomy', 'General Embryology', 'anatomy/general-anatomy-and-embryology/general-embryology'),
  ('anatomy', 'General Histology', 'anatomy/histology-genetics-and-applied-anatomy/general-histology'),
  ('anatomy', 'Genetics', 'anatomy/histology-genetics-and-applied-anatomy/genetics'),
  ('anatomy', 'Gluteal Region & Hip', 'anatomy/lower-limb/gluteal-region-and-hip'),
  ('anatomy', 'Heart & Pericardium', 'anatomy/thorax/heart-and-pericardium'),
  ('anatomy', 'Hepatobiliary & Pancreas', 'anatomy/abdomen-and-pelvis/hepatobiliary-and-pancreas'),
  ('anatomy', 'Introduction & General Anatomy', 'anatomy/general-anatomy-and-embryology/introduction-and-general-anatomy'),
  ('anatomy', 'Knee & Popliteal Fossa', 'anatomy/lower-limb/knee-and-popliteal-fossa'),
  ('anatomy', 'Leg', 'anatomy/lower-limb/leg'),
  ('anatomy', 'Lower Limb Osteology', 'anatomy/lower-limb/lower-limb-osteology'),
  ('anatomy', 'Lungs & Pleura', 'anatomy/thorax/lungs-and-pleura'),
  ('anatomy', 'Mediastinum', 'anatomy/thorax/mediastinum'),
  ('anatomy', 'Meninges & Venous Sinuses', 'anatomy/neuroanatomy/meninges-and-venous-sinuses'),
  ('anatomy', 'Neck', 'anatomy/head-and-neck/neck'),
  ('anatomy', 'Nose & Paranasal Sinuses', 'anatomy/head-and-neck/nose-and-paranasal-sinuses'),
  ('anatomy', 'Oral Cavity', 'anatomy/head-and-neck/oral-cavity'),
  ('anatomy', 'Orbit & Eye', 'anatomy/head-and-neck/orbit-and-eye'),
  ('anatomy', 'Pectoral Region & Axilla', 'anatomy/upper-limb/pectoral-region-and-axilla'),
  ('anatomy', 'Pelvis', 'anatomy/abdomen-and-pelvis/pelvis'),
  ('anatomy', 'Perineum', 'anatomy/abdomen-and-pelvis/perineum'),
  ('anatomy', 'Peritoneum', 'anatomy/abdomen-and-pelvis/peritoneum'),
  ('anatomy', 'Pharynx & Larynx', 'anatomy/head-and-neck/pharynx-and-larynx'),
  ('anatomy', 'Posterior Abdominal Wall', 'anatomy/abdomen-and-pelvis/posterior-abdominal-wall'),
  ('anatomy', 'Shoulder & Arm', 'anatomy/upper-limb/shoulder-and-arm'),
  ('anatomy', 'Skull', 'anatomy/head-and-neck/skull'),
  ('anatomy', 'Spinal Cord', 'anatomy/neuroanatomy/spinal-cord'),
  ('anatomy', 'Surface & Radiological Anatomy', 'anatomy/histology-genetics-and-applied-anatomy/surface-and-radiological-anatomy'),
  ('anatomy', 'Systemic Histology', 'anatomy/histology-genetics-and-applied-anatomy/systemic-histology'),
  ('anatomy', 'Thigh', 'anatomy/lower-limb/thigh'),
  ('anatomy', 'Thoracic Wall & Mediastinum', 'anatomy/thorax'),
  ('anatomy', 'Thoracic Wall', 'anatomy/thorax/thoracic-wall'),
  ('anatomy', 'Thyroid & Parathyroid', 'anatomy/head-and-neck/thyroid-and-parathyroid'),
  ('anatomy', 'Upper Limb Osteology', 'anatomy/upper-limb/upper-limb-osteology'),
  ('anatomy', 'Ventricles & CSF', 'anatomy/neuroanatomy/ventricles-and-csf'),
  ('anatomy', 'Wrist & Hand', 'anatomy/upper-limb/wrist-and-hand'),
  ('biochemistry', 'Acid-Base & Electrolytes', 'biochemistry/clinical-biochemistry/acid-base-and-electrolytes'),
  ('biochemistry', 'Amino Acids & Proteins', 'biochemistry/biomolecules-and-cell/amino-acids-and-proteins'),
  ('biochemistry', 'Bioenergetics', 'biochemistry/enzymes-and-bioenergetics/bioenergetics'),
  ('biochemistry', 'Biotechnology', 'biochemistry/molecular-biology-and-genetics/biotechnology'),
  ('biochemistry', 'Carbohydrates', 'biochemistry/biomolecules-and-cell/carbohydrates'),
  ('biochemistry', 'Cell & Membrane', 'biochemistry/biomolecules-and-cell/cell-and-membrane'),
  ('biochemistry', 'Cholesterol & Lipoproteins', 'biochemistry/lipid-metabolism/cholesterol-and-lipoproteins'),
  ('biochemistry', 'Clinical Correlations', 'biochemistry/carbohydrate-metabolism/clinical-correlations'),
  ('biochemistry', 'Core Pathways', 'biochemistry/carbohydrate-metabolism/core-pathways'),
  ('biochemistry', 'DNA', 'biochemistry/molecular-biology-and-genetics/dna'),
  ('biochemistry', 'Endocrine Biochemistry', 'biochemistry/clinical-biochemistry/endocrine-biochemistry'),
  ('biochemistry', 'Enzymes', 'biochemistry/enzymes-and-bioenergetics/enzymes'),
  ('biochemistry', 'Fat-Soluble Vitamins', 'biochemistry/vitamins-minerals-and-nutrition/fat-soluble-vitamins'),
  ('biochemistry', 'Fatty Acids', 'biochemistry/lipid-metabolism/fatty-acids'),
  ('biochemistry', 'Gene Regulation & Mutation', 'biochemistry/molecular-biology-and-genetics/gene-regulation-and-mutation'),
  ('biochemistry', 'Heme', 'biochemistry/heme-and-hemoglobin/heme'),
  ('biochemistry', 'Hemoglobin', 'biochemistry/heme-and-hemoglobin/hemoglobin'),
  ('biochemistry', 'Inborn Errors', 'biochemistry/amino-acid-and-protein-metabolism/inborn-errors'),
  ('biochemistry', 'Ketone Bodies', 'biochemistry/lipid-metabolism/ketone-bodies'),
  ('biochemistry', 'Kidney', 'biochemistry/clinical-biochemistry/kidney'),
  ('biochemistry', 'Laboratory Skills', 'biochemistry/clinical-biochemistry/laboratory-skills'),
  ('biochemistry', 'Lipids', 'biochemistry/biomolecules-and-cell/lipids'),
  ('biochemistry', 'Liver', 'biochemistry/clinical-biochemistry/liver'),
  ('biochemistry', 'Minerals', 'biochemistry/vitamins-minerals-and-nutrition/minerals'),
  ('biochemistry', 'Nitrogen Metabolism', 'biochemistry/amino-acid-and-protein-metabolism/nitrogen-metabolism'),
  ('biochemistry', 'Nucleotides', 'biochemistry/molecular-biology-and-genetics/nucleotides'),
  ('biochemistry', 'Nutrition', 'biochemistry/vitamins-minerals-and-nutrition/nutrition'),
  ('biochemistry', 'Other Clinical Topics', 'biochemistry/clinical-biochemistry/other-clinical-topics'),
  ('biochemistry', 'RNA & Protein Synthesis', 'biochemistry/molecular-biology-and-genetics/rna-and-protein-synthesis'),
  ('biochemistry', 'Selected Amino Acids', 'biochemistry/amino-acid-and-protein-metabolism/selected-amino-acids'),
  ('biochemistry', 'Water-Soluble Vitamins', 'biochemistry/vitamins-minerals-and-nutrition/water-soluble-vitamins'),
  ('community-medicine', 'Adolescent Health', 'community-medicine/maternal-child-and-adolescent-health/adolescent-health'),
  ('community-medicine', 'Air, Housing & Waste', 'community-medicine/environmental-and-occupational-health/air-housing-and-waste'),
  ('community-medicine', 'Assessment', 'community-medicine/nutrition/assessment'),
  ('community-medicine', 'Biostatistics', 'community-medicine/biostatistics-and-demography/biostatistics'),
  ('community-medicine', 'Child Health', 'community-medicine/maternal-child-and-adolescent-health/child-health'),
  ('community-medicine', 'Community Skills', 'community-medicine/field-and-practical-skills/community-skills'),
  ('community-medicine', 'Deficiencies', 'community-medicine/nutrition/deficiencies'),
  ('community-medicine', 'Demography', 'community-medicine/biostatistics-and-demography/demography'),
  ('community-medicine', 'Epidemiologic Measures', 'community-medicine/health-disease-and-epidemiology/epidemiologic-measures'),
  ('community-medicine', 'Family Study', 'community-medicine/field-and-practical-skills/family-study'),
  ('community-medicine', 'Family Welfare', 'community-medicine/health-system-programs-and-management/family-welfare'),
  ('community-medicine', 'Health & Disease', 'community-medicine/health-disease-and-epidemiology/health-and-disease'),
  ('community-medicine', 'Health Care Delivery', 'community-medicine/health-system-programs-and-management/health-care-delivery'),
  ('community-medicine', 'Health Planning', 'community-medicine/health-system-programs-and-management/health-planning'),
  ('community-medicine', 'Immunization', 'community-medicine/maternal-child-and-adolescent-health/immunization'),
  ('community-medicine', 'Major NCDs', 'community-medicine/non-communicable-diseases/major-ncds'),
  ('community-medicine', 'Maternal Health', 'community-medicine/maternal-child-and-adolescent-health/maternal-health'),
  ('community-medicine', 'National Programs', 'community-medicine/health-system-programs-and-management/national-programs'),
  ('community-medicine', 'Occupational Health', 'community-medicine/environmental-and-occupational-health/occupational-health'),
  ('community-medicine', 'Outbreak Investigation', 'community-medicine/health-disease-and-epidemiology/outbreak-investigation'),
  ('community-medicine', 'Programs', 'community-medicine/nutrition/programs'),
  ('community-medicine', 'Respiratory', 'community-medicine/communicable-diseases/respiratory'),
  ('community-medicine', 'Risk Factors', 'community-medicine/non-communicable-diseases/risk-factors'),
  ('community-medicine', 'STI & HIV', 'community-medicine/communicable-diseases/sti-and-hiv'),
  ('community-medicine', 'Screening', 'community-medicine/health-disease-and-epidemiology/screening'),
  ('community-medicine', 'Study Designs', 'community-medicine/health-disease-and-epidemiology/study-designs'),
  ('community-medicine', 'Vector-Borne', 'community-medicine/communicable-diseases/vector-borne'),
  ('community-medicine', 'Water & Sanitation', 'community-medicine/environmental-and-occupational-health/water-and-sanitation'),
  ('community-medicine', 'Water/Food-Borne', 'community-medicine/communicable-diseases/water-food-borne'),
  ('community-medicine', 'Zoonoses', 'community-medicine/communicable-diseases/zoonoses'),
  ('dermatology', 'Acne & Hair', 'dermatology/pigmentary-autoimmune-and-other/acne-and-hair'),
  ('dermatology', 'Allergic', 'dermatology/inflammatory-skin-disease/allergic'),
  ('dermatology', 'Bacterial', 'dermatology/infections-and-infestations/bacterial'),
  ('dermatology', 'Dermatitis', 'dermatology/inflammatory-skin-disease/dermatitis'),
  ('dermatology', 'Fungal', 'dermatology/infections-and-infestations/fungal'),
  ('dermatology', 'Infestations', 'dermatology/infections-and-infestations/infestations'),
  ('dermatology', 'Leprosy', 'dermatology/leprosy-and-stis/leprosy'),
  ('dermatology', 'Papulosquamous', 'dermatology/inflammatory-skin-disease/papulosquamous'),
  ('dermatology', 'Pigmentary', 'dermatology/pigmentary-autoimmune-and-other/pigmentary'),
  ('dermatology', 'STIs', 'dermatology/leprosy-and-stis/stis'),
  ('dermatology', 'Skills', 'dermatology/dermatology-skills/skills'),
  ('dermatology', 'Skin Basics', 'dermatology/approach-to-skin-disease/skin-basics'),
  ('dermatology', 'Vesiculobullous', 'dermatology/pigmentary-autoimmune-and-other/vesiculobullous'),
  ('dermatology', 'Viral', 'dermatology/infections-and-infestations/viral'),
  ('ent', 'Airway', 'ent/larynx-and-airway/airway'),
  ('ent', 'Clinical Anatomy & Examination', 'ent/ear/clinical-anatomy-and-examination'),
  ('ent', 'Examination', 'ent/ent-clinical-skills/examination'),
  ('ent', 'External Ear', 'ent/ear/external-ear'),
  ('ent', 'Hearing', 'ent/ear/hearing'),
  ('ent', 'Inner Ear', 'ent/ear/inner-ear'),
  ('ent', 'Larynx', 'ent/larynx-and-airway/larynx'),
  ('ent', 'Malignancy', 'ent/head-and-neck/malignancy'),
  ('ent', 'Middle Ear', 'ent/ear/middle-ear'),
  ('ent', 'Neck Swelling', 'ent/head-and-neck/neck-swelling'),
  ('ent', 'Nose', 'ent/nose-and-paranasal-sinuses/nose'),
  ('ent', 'Pharynx', 'ent/pharynx-and-oral-cavity/pharynx'),
  ('ent', 'Sinuses', 'ent/nose-and-paranasal-sinuses/sinuses'),
  ('ent', 'Tonsil & Adenoid', 'ent/pharynx-and-oral-cavity/tonsil-and-adenoid'),
  ('forensic-medicine', 'Animal Poisons', 'forensic-medicine/toxicology/animal-poisons'),
  ('forensic-medicine', 'Asphyxia', 'forensic-medicine/asphyxial-deaths/asphyxia'),
  ('forensic-medicine', 'Autopsy', 'forensic-medicine/thanatology/autopsy'),
  ('forensic-medicine', 'CNS Poisons', 'forensic-medicine/toxicology/cns-poisons'),
  ('forensic-medicine', 'Certificates', 'forensic-medicine/documentation-and-practicals/certificates'),
  ('forensic-medicine', 'Common Gases', 'forensic-medicine/toxicology/common-gases'),
  ('forensic-medicine', 'Corrosives & Irritants', 'forensic-medicine/toxicology/corrosives-and-irritants'),
  ('forensic-medicine', 'Death', 'forensic-medicine/thanatology/death'),
  ('forensic-medicine', 'Firearm Injuries', 'forensic-medicine/injuries/firearm-injuries'),
  ('forensic-medicine', 'General Toxicology', 'forensic-medicine/toxicology/general-toxicology'),
  ('forensic-medicine', 'Identification', 'forensic-medicine/forensic-medicine-and-law/identification'),
  ('forensic-medicine', 'Legal Procedures', 'forensic-medicine/forensic-medicine-and-law/legal-procedures'),
  ('forensic-medicine', 'Mechanical Injuries', 'forensic-medicine/injuries/mechanical-injuries'),
  ('forensic-medicine', 'Medical Jurisprudence', 'forensic-medicine/forensic-medicine-and-law/medical-jurisprudence'),
  ('forensic-medicine', 'Pesticides', 'forensic-medicine/toxicology/pesticides'),
  ('forensic-medicine', 'Plant Poisons', 'forensic-medicine/toxicology/plant-poisons'),
  ('forensic-medicine', 'Postmortem Changes', 'forensic-medicine/thanatology/postmortem-changes'),
  ('forensic-medicine', 'Pregnancy & Delivery', 'forensic-medicine/sexual-and-reproductive-forensics/pregnancy-and-delivery'),
  ('forensic-medicine', 'Regional & Special Injuries', 'forensic-medicine/injuries/regional-and-special-injuries'),
  ('forensic-medicine', 'Reports', 'forensic-medicine/documentation-and-practicals/reports'),
  ('forensic-medicine', 'Sexual Offences', 'forensic-medicine/sexual-and-reproductive-forensics/sexual-offences'),
  ('forensic-medicine', 'Thermal & Electrical', 'forensic-medicine/injuries/thermal-and-electrical'),
  ('general-medicine', 'Airway Disease', 'general-medicine/respiratory-medicine/airway-disease'),
  ('general-medicine', 'Anemia', 'general-medicine/hematology-and-oncology/anemia'),
  ('general-medicine', 'Arrhythmias', 'general-medicine/cardiovascular-medicine/arrhythmias'),
  ('general-medicine', 'Bleeding', 'general-medicine/hematology-and-oncology/bleeding'),
  ('general-medicine', 'Blood Malignancy', 'general-medicine/hematology-and-oncology/blood-malignancy'),
  ('general-medicine', 'CNS Infection', 'general-medicine/neurology/cns-infection'),
  ('general-medicine', 'Cardiology', 'general-medicine/cardiovascular-medicine'),
  ('general-medicine', 'Cerebrovascular', 'general-medicine/neurology/cerebrovascular'),
  ('general-medicine', 'Clinical Methods', 'general-medicine/clinical-methods-and-emergency-approach/clinical-methods'),
  ('general-medicine', 'Common Presentations', 'general-medicine/clinical-methods-and-emergency-approach/common-presentations'),
  ('general-medicine', 'Diabetes', 'general-medicine/endocrinology-and-metabolism/diabetes'),
  ('general-medicine', 'Electrolytes & Acid-Base', 'general-medicine/renal-and-electrolytes/electrolytes-and-acid-base'),
  ('general-medicine', 'Emergency Basics', 'general-medicine/clinical-methods-and-emergency-approach/emergency-basics'),
  ('general-medicine', 'Endocrinology & Nephrology', 'general-medicine/endocrinology-and-metabolism'),
  ('general-medicine', 'Fever', 'general-medicine/infectious-and-tropical-medicine/fever'),
  ('general-medicine', 'HIV', 'general-medicine/infectious-and-tropical-medicine/hiv'),
  ('general-medicine', 'Heart Failure', 'general-medicine/cardiovascular-medicine/heart-failure'),
  ('general-medicine', 'Hypertension', 'general-medicine/cardiovascular-medicine/hypertension'),
  ('general-medicine', 'Infections', 'general-medicine/respiratory-medicine/infections'),
  ('general-medicine', 'Interpretation', 'general-medicine/medicine-clinical-skills/interpretation'),
  ('general-medicine', 'Intestinal', 'general-medicine/gastroenterology-and-hepatology/intestinal'),
  ('general-medicine', 'Ischemic Heart Disease', 'general-medicine/cardiovascular-medicine/ischemic-heart-disease'),
  ('general-medicine', 'Kidney Disease', 'general-medicine/renal-and-electrolytes/kidney-disease'),
  ('general-medicine', 'Liver', 'general-medicine/gastroenterology-and-hepatology/liver'),
  ('general-medicine', 'Neurology & Infectious Disease', 'general-medicine/neurology'),
  ('general-medicine', 'Nutrition', 'general-medicine/rheumatology-toxicology-and-miscellaneous/nutrition'),
  ('general-medicine', 'Oncology', 'general-medicine/hematology-and-oncology/oncology'),
  ('general-medicine', 'Other Endocrine', 'general-medicine/endocrinology-and-metabolism/other-endocrine'),
  ('general-medicine', 'Other', 'general-medicine/neurology/other'),
  ('general-medicine', 'Pleural Disease', 'general-medicine/respiratory-medicine/pleural-disease'),
  ('general-medicine', 'Poisoning', 'general-medicine/rheumatology-toxicology-and-miscellaneous/poisoning'),
  ('general-medicine', 'Respiratory Medicine', 'general-medicine/respiratory-medicine'),
  ('general-medicine', 'Rheumatology', 'general-medicine/rheumatology-toxicology-and-miscellaneous/rheumatology'),
  ('general-medicine', 'Seizures', 'general-medicine/neurology/seizures'),
  ('general-medicine', 'System Examination', 'general-medicine/medicine-clinical-skills/system-examination'),
  ('general-medicine', 'Thyroid', 'general-medicine/endocrinology-and-metabolism/thyroid'),
  ('general-medicine', 'Tropical', 'general-medicine/infectious-and-tropical-medicine/tropical'),
  ('general-medicine', 'Upper GI', 'general-medicine/gastroenterology-and-hepatology/upper-gi'),
  ('general-medicine', 'Urinary', 'general-medicine/renal-and-electrolytes/urinary'),
  ('general-medicine', 'Valvular Disease', 'general-medicine/cardiovascular-medicine/valvular-disease'),
  ('general-surgery', 'Abdominal Trauma', 'general-surgery/trauma/abdominal-trauma'),
  ('general-surgery', 'Anorectal', 'general-surgery/gastrointestinal-surgery/anorectal'),
  ('general-surgery', 'Biliary', 'general-surgery/hepatobiliary-and-pancreas/biliary'),
  ('general-surgery', 'Breast', 'general-surgery/breast-and-endocrine-surgery/breast'),
  ('general-surgery', 'Clinical Skills', 'general-surgery/surgical-oncology-and-skills/clinical-skills'),
  ('general-surgery', 'Esophagus & Stomach', 'general-surgery/gastrointestinal-surgery/esophagus-and-stomach'),
  ('general-surgery', 'Fluids, Blood & Nutrition', 'general-surgery/principles-of-surgery/fluids-blood-and-nutrition'),
  ('general-surgery', 'Head & Chest Trauma', 'general-surgery/trauma/head-and-chest-trauma'),
  ('general-surgery', 'Hernias', 'general-surgery/gastrointestinal-surgery/hernias'),
  ('general-surgery', 'Initial Trauma Care', 'general-surgery/trauma/initial-trauma-care'),
  ('general-surgery', 'Obstruction', 'general-surgery/urology/obstruction'),
  ('general-surgery', 'Oncology', 'general-surgery/surgical-oncology-and-skills/oncology'),
  ('general-surgery', 'Other', 'general-surgery/urology/other'),
  ('general-surgery', 'Pancreas', 'general-surgery/hepatobiliary-and-pancreas/pancreas'),
  ('general-surgery', 'Perioperative Care', 'general-surgery/principles-of-surgery/perioperative-care'),
  ('general-surgery', 'Shock', 'general-surgery/principles-of-surgery/shock'),
  ('general-surgery', 'Skin & Soft Tissue', 'general-surgery/vascular-and-soft-tissue/skin-and-soft-tissue'),
  ('general-surgery', 'Small & Large Bowel', 'general-surgery/gastrointestinal-surgery/small-and-large-bowel'),
  ('general-surgery', 'Thyroid', 'general-surgery/breast-and-endocrine-surgery/thyroid'),
  ('general-surgery', 'Urinary Stones', 'general-surgery/urology/urinary-stones'),
  ('general-surgery', 'Vascular', 'general-surgery/vascular-and-soft-tissue/vascular'),
  ('general-surgery', 'Wounds & Infection', 'general-surgery/principles-of-surgery/wounds-and-infection'),
  ('microbiology', 'Adaptive Immunity', 'microbiology/immunology/adaptive-immunity'),
  ('microbiology', 'Anaerobes', 'microbiology/bacteriology/anaerobes'),
  ('microbiology', 'Antigen-Antibody Reactions', 'microbiology/immunology/antigen-antibody-reactions'),
  ('microbiology', 'Bacterial Structure & Growth', 'microbiology/general-microbiology-and-infection-control/bacterial-structure-and-growth'),
  ('microbiology', 'Bloodstream & CVS', 'microbiology/system-based-diagnostic-microbiology/bloodstream-and-cvs'),
  ('microbiology', 'CNS', 'microbiology/system-based-diagnostic-microbiology/cns'),
  ('microbiology', 'DNA Viruses', 'microbiology/virology/dna-viruses'),
  ('microbiology', 'Enteric Gram-Negative Bacilli', 'microbiology/bacteriology/enteric-gram-negative-bacilli'),
  ('microbiology', 'GIT', 'microbiology/system-based-diagnostic-microbiology/git'),
  ('microbiology', 'General Microbiology', 'microbiology/general-microbiology-and-infection-control'),
  ('microbiology', 'General Virology', 'microbiology/virology/general-virology'),
  ('microbiology', 'Genital Tract', 'microbiology/system-based-diagnostic-microbiology/genital-tract'),
  ('microbiology', 'Gram Negative Organisms', 'microbiology/bacteriology'),
  ('microbiology', 'Gram Positive Cocci & Bacilli', 'microbiology/bacteriology'),
  ('microbiology', 'Gram-Negative Cocci', 'microbiology/bacteriology/gram-negative-cocci'),
  ('microbiology', 'Gram-Positive Bacilli', 'microbiology/bacteriology/gram-positive-bacilli'),
  ('microbiology', 'Gram-Positive Cocci', 'microbiology/bacteriology/gram-positive-cocci'),
  ('microbiology', 'Healthcare-Associated Infection', 'microbiology/general-microbiology-and-infection-control/healthcare-associated-infection'),
  ('microbiology', 'Helminths', 'microbiology/parasitology/helminths'),
  ('microbiology', 'Hypersensitivity', 'microbiology/immunology/hypersensitivity'),
  ('microbiology', 'Immunoprophylaxis', 'microbiology/immunology/immunoprophylaxis'),
  ('microbiology', 'Innate Immunity', 'microbiology/immunology/innate-immunity'),
  ('microbiology', 'Microbial Genetics', 'microbiology/general-microbiology-and-infection-control/microbial-genetics'),
  ('microbiology', 'Mycobacteria, Virology & Immunology', 'microbiology'),
  ('microbiology', 'Mycobacteria', 'microbiology/bacteriology/mycobacteria'),
  ('microbiology', 'Opportunistic & Systemic', 'microbiology/mycology/opportunistic-and-systemic'),
  ('microbiology', 'Other Gram-Negative Bacilli', 'microbiology/bacteriology/other-gram-negative-bacilli'),
  ('microbiology', 'Protozoa', 'microbiology/parasitology/protozoa'),
  ('microbiology', 'RNA Viruses', 'microbiology/virology/rna-viruses'),
  ('microbiology', 'Respiratory', 'microbiology/system-based-diagnostic-microbiology/respiratory'),
  ('microbiology', 'Spirochetes & Others', 'microbiology/bacteriology/spirochetes-and-others'),
  ('microbiology', 'Staining', 'microbiology/general-microbiology-and-infection-control/staining'),
  ('microbiology', 'Sterilization & Disinfection', 'microbiology/general-microbiology-and-infection-control/sterilization-and-disinfection'),
  ('microbiology', 'Superficial & Cutaneous', 'microbiology/mycology/superficial-and-cutaneous'),
  ('microbiology', 'Urinary', 'microbiology/system-based-diagnostic-microbiology/urinary'),
  ('obgyn', 'Abnormal Labour', 'obgyn/normal-and-abnormal-labour/abnormal-labour'),
  ('obgyn', 'Antenatal Care', 'obgyn/normal-pregnancy-and-antenatal-care/antenatal-care'),
  ('obgyn', 'Benign Disorders', 'obgyn/general-gynaecology/benign-disorders'),
  ('obgyn', 'Cervix', 'obgyn/gynaecologic-oncology/cervix'),
  ('obgyn', 'Contraception', 'obgyn/reproductive-medicine-and-family-planning/contraception'),
  ('obgyn', 'Endometrium & Ovary', 'obgyn/gynaecologic-oncology/endometrium-and-ovary'),
  ('obgyn', 'Gynaecology I', 'obgyn/general-gynaecology'),
  ('obgyn', 'Gynaecology II', 'obgyn/gynaecologic-oncology'),
  ('obgyn', 'Gynaecology', 'obgyn/obg-clinical-skills/gynaecology'),
  ('obgyn', 'Hemorrhage', 'obgyn/high-risk-pregnancy/hemorrhage'),
  ('obgyn', 'High-Risk Obstetrics', 'obgyn/high-risk-pregnancy'),
  ('obgyn', 'Hypertensive Disorders', 'obgyn/high-risk-pregnancy/hypertensive-disorders'),
  ('obgyn', 'Infections', 'obgyn/general-gynaecology/infections'),
  ('obgyn', 'Infertility', 'obgyn/reproductive-medicine-and-family-planning/infertility'),
  ('obgyn', 'Medical Disorders', 'obgyn/high-risk-pregnancy/medical-disorders'),
  ('obgyn', 'Menstrual Disorders', 'obgyn/general-gynaecology/menstrual-disorders'),
  ('obgyn', 'Newborn', 'obgyn/puerperium-and-newborn/newborn'),
  ('obgyn', 'Normal Labour', 'obgyn/normal-and-abnormal-labour/normal-labour'),
  ('obgyn', 'Normal Pregnancy', 'obgyn/normal-pregnancy-and-antenatal-care'),
  ('obgyn', 'Obstetric', 'obgyn/obg-clinical-skills/obstetric'),
  ('obgyn', 'Operative Obstetrics', 'obgyn/normal-and-abnormal-labour/operative-obstetrics'),
  ('obgyn', 'Other', 'obgyn/high-risk-pregnancy/other'),
  ('obgyn', 'Pregnancy Physiology', 'obgyn/normal-pregnancy-and-antenatal-care/pregnancy-physiology'),
  ('obgyn', 'Puerperium', 'obgyn/puerperium-and-newborn/puerperium'),
  ('ophthalmology', 'Blindness', 'ophthalmology/community-ophthalmology-and-skills/blindness'),
  ('ophthalmology', 'Conjunctiva', 'ophthalmology/adnexa-and-conjunctiva/conjunctiva'),
  ('ophthalmology', 'Cornea', 'ophthalmology/cornea-sclera-and-uvea/cornea'),
  ('ophthalmology', 'Examination', 'ophthalmology/optics-examination-and-refraction/examination'),
  ('ophthalmology', 'Eyelid', 'ophthalmology/adnexa-and-conjunctiva/eyelid'),
  ('ophthalmology', 'Glaucoma', 'ophthalmology/lens-and-glaucoma/glaucoma'),
  ('ophthalmology', 'Lacrimal', 'ophthalmology/adnexa-and-conjunctiva/lacrimal'),
  ('ophthalmology', 'Lens', 'ophthalmology/lens-and-glaucoma/lens'),
  ('ophthalmology', 'Neuro-ophthalmology', 'ophthalmology/squint-neuro-ophthalmology-and-trauma/neuro-ophthalmology'),
  ('ophthalmology', 'Optic Nerve', 'ophthalmology/retina-and-optic-nerve/optic-nerve'),
  ('ophthalmology', 'Refraction', 'ophthalmology/optics-examination-and-refraction/refraction'),
  ('ophthalmology', 'Retina', 'ophthalmology/retina-and-optic-nerve/retina'),
  ('ophthalmology', 'Sclera', 'ophthalmology/cornea-sclera-and-uvea/sclera'),
  ('ophthalmology', 'Skills', 'ophthalmology/community-ophthalmology-and-skills/skills'),
  ('ophthalmology', 'Squint', 'ophthalmology/squint-neuro-ophthalmology-and-trauma/squint'),
  ('ophthalmology', 'Trauma', 'ophthalmology/squint-neuro-ophthalmology-and-trauma/trauma'),
  ('ophthalmology', 'Uvea', 'ophthalmology/cornea-sclera-and-uvea/uvea'),
  ('orthopaedics', 'Arthritis', 'orthopaedics/degenerative-and-inflammatory-joint-disease/arthritis'),
  ('orthopaedics', 'Complications', 'orthopaedics/fractures-and-trauma-principles/complications'),
  ('orthopaedics', 'Examination', 'orthopaedics/orthopaedic-skills/examination'),
  ('orthopaedics', 'Fracture Basics', 'orthopaedics/fractures-and-trauma-principles/fracture-basics'),
  ('orthopaedics', 'Imaging', 'orthopaedics/orthopaedic-skills/imaging'),
  ('orthopaedics', 'Infection', 'orthopaedics/bone-and-joint-infection/infection'),
  ('orthopaedics', 'Lower Limb', 'orthopaedics/regional-trauma/lower-limb'),
  ('orthopaedics', 'Metabolic', 'orthopaedics/metabolic-tumor-and-pediatric-orthopaedics/metabolic'),
  ('orthopaedics', 'Pediatric', 'orthopaedics/metabolic-tumor-and-pediatric-orthopaedics/pediatric'),
  ('orthopaedics', 'Spine & Pelvis', 'orthopaedics/regional-trauma/spine-and-pelvis'),
  ('orthopaedics', 'Tumors', 'orthopaedics/metabolic-tumor-and-pediatric-orthopaedics/tumors'),
  ('orthopaedics', 'Upper Limb', 'orthopaedics/regional-trauma/upper-limb'),
  ('paediatrics', 'Cardiovascular', 'paediatrics/systemic-pediatrics/cardiovascular'),
  ('paediatrics', 'Common Infections', 'paediatrics/immunization-and-infections/common-infections'),
  ('paediatrics', 'Common Problems', 'paediatrics/neonatology/common-problems'),
  ('paediatrics', 'Development', 'paediatrics/growth-and-development/development'),
  ('paediatrics', 'Emergencies', 'paediatrics/pediatric-emergencies-and-skills/emergencies'),
  ('paediatrics', 'Feeding', 'paediatrics/nutrition/feeding'),
  ('paediatrics', 'Growth', 'paediatrics/growth-and-development/growth'),
  ('paediatrics', 'Hematology', 'paediatrics/systemic-pediatrics/hematology'),
  ('paediatrics', 'Immunization', 'paediatrics/immunization-and-infections/immunization'),
  ('paediatrics', 'Malnutrition', 'paediatrics/nutrition/malnutrition'),
  ('paediatrics', 'Neurology', 'paediatrics/systemic-pediatrics/neurology'),
  ('paediatrics', 'Normal Newborn', 'paediatrics/neonatology/normal-newborn'),
  ('paediatrics', 'Renal', 'paediatrics/systemic-pediatrics/renal'),
  ('paediatrics', 'Respiratory', 'paediatrics/systemic-pediatrics/respiratory'),
  ('paediatrics', 'Skills', 'paediatrics/pediatric-emergencies-and-skills/skills'),
  ('pathology', 'Anemias', 'pathology/hematology/anemias'),
  ('pathology', 'Blood Bank', 'pathology/hematology/blood-bank'),
  ('pathology', 'Bone & Soft Tissue', 'pathology/systemic-pathology/bone-and-soft-tissue'),
  ('pathology', 'Breast', 'pathology/systemic-pathology/breast'),
  ('pathology', 'CNS', 'pathology/systemic-pathology/cns'),
  ('pathology', 'Cardiovascular & Respiratory', 'pathology/systemic-pathology'),
  ('pathology', 'Cardiovascular', 'pathology/systemic-pathology/cardiovascular'),
  ('pathology', 'Cell Injury & Adaptation', 'pathology/general-pathology/cell-injury-and-adaptation'),
  ('pathology', 'Cell Injury & Inflammation Basics', 'pathology/general-pathology'),
  ('pathology', 'Clinical Pathology', 'pathology/pathology-practicals/clinical-pathology'),
  ('pathology', 'Endocrine & Nervous System', 'pathology/systemic-pathology'),
  ('pathology', 'Endocrine', 'pathology/systemic-pathology/endocrine'),
  ('pathology', 'Female Genital', 'pathology/systemic-pathology/female-genital'),
  ('pathology', 'GIT, Liver & Renal', 'pathology/systemic-pathology'),
  ('pathology', 'GIT', 'pathology/systemic-pathology/git'),
  ('pathology', 'Gross Specimens', 'pathology/pathology-practicals/gross-specimens'),
  ('pathology', 'Haematology', 'pathology/hematology'),
  ('pathology', 'Healing & Repair', 'pathology/general-pathology/healing-and-repair'),
  ('pathology', 'Hemodynamic Disorders', 'pathology/general-pathology/hemodynamic-disorders'),
  ('pathology', 'Hemostasis', 'pathology/hematology/hemostasis'),
  ('pathology', 'Hepatobiliary & Pancreas', 'pathology/systemic-pathology/hepatobiliary-and-pancreas'),
  ('pathology', 'Immunopathology', 'pathology/general-pathology/immunopathology'),
  ('pathology', 'Inflammation, Healing & Haemodynamics', 'pathology/general-pathology'),
  ('pathology', 'Inflammation', 'pathology/general-pathology/inflammation'),
  ('pathology', 'Lymphoid Disorders', 'pathology/hematology/lymphoid-disorders'),
  ('pathology', 'Male Genital', 'pathology/systemic-pathology/male-genital'),
  ('pathology', 'Microscopy', 'pathology/pathology-practicals/microscopy'),
  ('pathology', 'Neoplasia & Genetics', 'pathology/general-pathology/neoplasia'),
  ('pathology', 'Neoplasia', 'pathology/general-pathology/neoplasia'),
  ('pathology', 'Renal', 'pathology/systemic-pathology/renal'),
  ('pathology', 'Respiratory', 'pathology/systemic-pathology/respiratory'),
  ('pathology', 'Thrombosis, Shock & Immunopathology', 'pathology/general-pathology'),
  ('pathology', 'WBC Disorders', 'pathology/hematology/wbc-disorders'),
  ('pharmacology', 'ANS Toxicology Link', 'pharmacology/autonomic-nervous-system/ans-toxicology-link'),
  ('pharmacology', 'Adrenergic Drugs', 'pharmacology/autonomic-nervous-system/adrenergic-drugs'),
  ('pharmacology', 'Anaesthetic Drugs', 'pharmacology/cns/anaesthetic-drugs'),
  ('pharmacology', 'Angina & Ischemic Heart Disease', 'pharmacology/cardiovascular-and-renal/angina-and-ischemic-heart-disease'),
  ('pharmacology', 'Antibacterials', 'pharmacology/antimicrobial-chemotherapy/antibacterials'),
  ('pharmacology', 'Anticancer', 'pharmacology/antimicrobial-chemotherapy/anticancer'),
  ('pharmacology', 'Antiepileptics', 'pharmacology/cns/antiepileptics'),
  ('pharmacology', 'Antifungal', 'pharmacology/antimicrobial-chemotherapy/antifungal'),
  ('pharmacology', 'Antileprosy', 'pharmacology/antimicrobial-chemotherapy/antileprosy'),
  ('pharmacology', 'Antiparasitic', 'pharmacology/antimicrobial-chemotherapy/antiparasitic'),
  ('pharmacology', 'Antitubercular', 'pharmacology/antimicrobial-chemotherapy/antitubercular'),
  ('pharmacology', 'Antiviral', 'pharmacology/antimicrobial-chemotherapy/antiviral'),
  ('pharmacology', 'Arrhythmias', 'pharmacology/cardiovascular-and-renal/arrhythmias'),
  ('pharmacology', 'Asthma & COPD', 'pharmacology/autacoids-and-respiratory/asthma-and-copd'),
  ('pharmacology', 'Autacoids', 'pharmacology/autacoids-and-respiratory/autacoids'),
  ('pharmacology', 'CNS Pharmacology', 'pharmacology/cns'),
  ('pharmacology', 'Chemotherapy', 'pharmacology/antimicrobial-chemotherapy'),
  ('pharmacology', 'Cholinergic & Adrenergic Systems', 'pharmacology/autonomic-nervous-system'),
  ('pharmacology', 'Cholinergic Drugs', 'pharmacology/autonomic-nervous-system/cholinergic-drugs'),
  ('pharmacology', 'Coagulation', 'pharmacology/cardiovascular-and-renal/coagulation'),
  ('pharmacology', 'Communication & Safety', 'pharmacology/clinical-pharmacology-and-practicals/communication-and-safety'),
  ('pharmacology', 'Corticosteroids', 'pharmacology/endocrine-and-git/corticosteroids'),
  ('pharmacology', 'Diabetes', 'pharmacology/endocrine-and-git/diabetes'),
  ('pharmacology', 'Diuretics', 'pharmacology/cardiovascular-and-renal/diuretics'),
  ('pharmacology', 'Drug Delivery', 'pharmacology/clinical-pharmacology-and-practicals/drug-delivery'),
  ('pharmacology', 'Drug Safety & Rational Use', 'pharmacology/general-pharmacology/drug-safety-and-rational-use'),
  ('pharmacology', 'GIT', 'pharmacology/endocrine-and-git/git'),
  ('pharmacology', 'General Pharmacology', 'pharmacology/general-pharmacology'),
  ('pharmacology', 'Heart Failure', 'pharmacology/cardiovascular-and-renal/heart-failure'),
  ('pharmacology', 'Hypertension', 'pharmacology/cardiovascular-and-renal/hypertension'),
  ('pharmacology', 'NSAIDs', 'pharmacology/autacoids-and-respiratory/nsaids'),
  ('pharmacology', 'Pain', 'pharmacology/cns/pain'),
  ('pharmacology', 'Parkinsonism', 'pharmacology/cns/parkinsonism'),
  ('pharmacology', 'Pharmacodynamics', 'pharmacology/general-pharmacology/pharmacodynamics'),
  ('pharmacology', 'Pharmacokinetics', 'pharmacology/general-pharmacology/pharmacokinetics'),
  ('pharmacology', 'Prescription Skills', 'pharmacology/clinical-pharmacology-and-practicals/prescription-skills'),
  ('pharmacology', 'Principles', 'pharmacology/antimicrobial-chemotherapy/principles'),
  ('pharmacology', 'Psychopharmacology', 'pharmacology/cns/psychopharmacology'),
  ('pharmacology', 'Reproductive', 'pharmacology/endocrine-and-git/reproductive'),
  ('pharmacology', 'Sedatives & Anxiolytics', 'pharmacology/cns/sedatives-and-anxiolytics'),
  ('pharmacology', 'Thyroid', 'pharmacology/endocrine-and-git/thyroid'),
  ('physiology', 'Adrenal', 'physiology/endocrine-and-reproductive-physiology/adrenal'),
  ('physiology', 'Autonomic Nervous System', 'physiology/central-nervous-system-and-special-senses/autonomic-nervous-system'),
  ('physiology', 'Blood & Body Fluids', 'physiology/blood-and-immunity'),
  ('physiology', 'Blood Groups', 'physiology/blood-and-immunity/blood-groups'),
  ('physiology', 'Cardiac Physiology', 'physiology/cardiovascular-system'),
  ('physiology', 'Cell Physiology', 'physiology/general-physiology/cell-physiology'),
  ('physiology', 'Circulation', 'physiology/cardiovascular-system/circulation'),
  ('physiology', 'Clinical Practicals', 'physiology/integrated-and-applied-physiology/clinical-practicals'),
  ('physiology', 'Concentration & Dilution', 'physiology/renal-physiology/concentration-and-dilution'),
  ('physiology', 'Digestion & Absorption', 'physiology/gastrointestinal-system/digestion-and-absorption'),
  ('physiology', 'Environmental Physiology', 'physiology/integrated-and-applied-physiology/environmental-physiology'),
  ('physiology', 'Exercise', 'physiology/integrated-and-applied-physiology/exercise'),
  ('physiology', 'Female Reproduction', 'physiology/endocrine-and-reproductive-physiology/female-reproduction'),
  ('physiology', 'Fluid, Electrolyte & Acid-Base', 'physiology/renal-physiology/fluid-electrolyte-and-acid-base'),
  ('physiology', 'Gas Exchange & Transport', 'physiology/respiratory-system/gas-exchange-and-transport'),
  ('physiology', 'General CNS', 'physiology/central-nervous-system-and-special-senses/general-cns'),
  ('physiology', 'General Endocrine', 'physiology/endocrine-and-reproductive-physiology/general-endocrine'),
  ('physiology', 'Hearing & Vestibular', 'physiology/central-nervous-system-and-special-senses/hearing-and-vestibular'),
  ('physiology', 'Heart', 'physiology/cardiovascular-system/heart'),
  ('physiology', 'Hemostasis', 'physiology/blood-and-immunity/hemostasis'),
  ('physiology', 'Higher Functions', 'physiology/central-nervous-system-and-special-senses/higher-functions'),
  ('physiology', 'Homeostasis & Body Fluids', 'physiology/general-physiology/homeostasis-and-body-fluids'),
  ('physiology', 'Male Reproduction', 'physiology/endocrine-and-reproductive-physiology/male-reproduction'),
  ('physiology', 'Micturition', 'physiology/renal-physiology/micturition'),
  ('physiology', 'Motility', 'physiology/gastrointestinal-system/motility'),
  ('physiology', 'Motor System', 'physiology/central-nervous-system-and-special-senses/motor-system'),
  ('physiology', 'Muscle', 'physiology/nerve-and-muscle/muscle'),
  ('physiology', 'Nerve', 'physiology/nerve-and-muscle/nerve'),
  ('physiology', 'Neuromuscular Junction', 'physiology/nerve-and-muscle/neuromuscular-junction'),
  ('physiology', 'Pancreas', 'physiology/endocrine-and-reproductive-physiology/pancreas'),
  ('physiology', 'Pituitary', 'physiology/endocrine-and-reproductive-physiology/pituitary'),
  ('physiology', 'RBC & Hemoglobin', 'physiology/blood-and-immunity/rbc-and-hemoglobin'),
  ('physiology', 'Regulation', 'physiology/respiratory-system/regulation'),
  ('physiology', 'Renal & GIT Physiology', 'physiology/renal-physiology'),
  ('physiology', 'Renal Hemodynamics', 'physiology/renal-physiology/renal-hemodynamics'),
  ('physiology', 'Respiratory Physiology', 'physiology/respiratory-system'),
  ('physiology', 'Secretions', 'physiology/gastrointestinal-system/secretions'),
  ('physiology', 'Sensory System', 'physiology/central-nervous-system-and-special-senses/sensory-system'),
  ('physiology', 'Taste & Smell', 'physiology/central-nervous-system-and-special-senses/taste-and-smell'),
  ('physiology', 'Temperature', 'physiology/integrated-and-applied-physiology/temperature'),
  ('physiology', 'Thyroid & Parathyroid', 'physiology/endocrine-and-reproductive-physiology/thyroid-and-parathyroid'),
  ('physiology', 'Tubular Functions', 'physiology/renal-physiology/tubular-functions'),
  ('physiology', 'Ventilation', 'physiology/respiratory-system/ventilation'),
  ('physiology', 'Vision', 'physiology/central-nervous-system-and-special-senses/vision'),
  ('physiology', 'WBC & Immunity', 'physiology/blood-and-immunity/wbc-and-immunity'),
  ('psychiatry', 'Anxiety', 'psychiatry/mood-and-anxiety-disorders/anxiety'),
  ('psychiatry', 'Child', 'psychiatry/organic-child-and-other-disorders/child'),
  ('psychiatry', 'Community', 'psychiatry/psychiatric-emergencies-and-community/community'),
  ('psychiatry', 'Emergencies', 'psychiatry/psychiatric-emergencies-and-community/emergencies'),
  ('psychiatry', 'Mood', 'psychiatry/mood-and-anxiety-disorders/mood'),
  ('psychiatry', 'Organic', 'psychiatry/organic-child-and-other-disorders/organic'),
  ('psychiatry', 'Psychiatric Assessment', 'psychiatry/assessment-and-foundations/psychiatric-assessment'),
  ('psychiatry', 'Psychosis', 'psychiatry/psychotic-disorders/psychosis'),
  ('psychiatry', 'Skills', 'psychiatry/psychiatry-skills/skills'),
  ('psychiatry', 'Somatic/Dissociative', 'psychiatry/organic-child-and-other-disorders/somatic-dissociative'),
  ('psychiatry', 'Substances', 'psychiatry/substance-use/substances'),
  ('radiodiagnosis', 'CT/MRI', 'radiodiagnosis/neuroimaging/ct-mri'),
  ('radiodiagnosis', 'Chest X-ray', 'radiodiagnosis/chest-imaging/chest-x-ray'),
  ('radiodiagnosis', 'Image Reading', 'radiodiagnosis/common-clinical-imaging-and-skills/image-reading'),
  ('radiodiagnosis', 'Modalities', 'radiodiagnosis/imaging-principles-and-safety/modalities'),
  ('radiodiagnosis', 'Modality Selection', 'radiodiagnosis/common-clinical-imaging-and-skills/modality-selection'),
  ('radiodiagnosis', 'Safety', 'radiodiagnosis/imaging-principles-and-safety/safety'),
  ('radiodiagnosis', 'X-ray & Ultrasound', 'radiodiagnosis/abdominal-imaging/x-ray-and-ultrasound'),
  ('radiodiagnosis', 'X-ray', 'radiodiagnosis/musculoskeletal-imaging/x-ray')
) AS m(subject_slug, week_title, ref)
JOIN "roadmap_weeks" rw ON rw."title" = m.week_title
JOIN "roadmaps" r ON r."id" = rw."roadmap_id"
JOIN "subjects" s ON s."id" = r."subject_id" AND s."slug" = m.subject_slug
WHERE rt."week_id" = rw."id";--> statement-breakpoint

-- The seeded content, by name. Anything an admin typed by hand that does not appear here
-- keeps its row and simply becomes unfiled: a material with no ref is a general cohort
-- material, and a quiz with no ref is not offered until someone files it.
UPDATE "quizzes" AS qz
SET "curriculum_ref" = m.ref
FROM (VALUES
  ('Acute Inflammation — vascular and cellular events', 'pathology/general-pathology/inflammation'),
  ('Necrosis — patterns and mechanisms', 'pathology/general-pathology/cell-injury-and-adaptation'),
  ('Neoplasia — nomenclature and characteristics', 'pathology/general-pathology/neoplasia'),
  ('Pharmacokinetics — absorption and distribution', 'pharmacology/general-pharmacology/pharmacokinetics'),
  ('Antitubercular Drugs', 'pharmacology/antimicrobial-chemotherapy/antitubercular'),
  ('Brachial Plexus', 'anatomy/upper-limb/pectoral-region-and-axilla'),
  ('ECG — basis and interpretation', 'physiology/cardiovascular-system/heart'),
  ('Mycobacterium tuberculosis', 'microbiology/bacteriology/mycobacteria'),
  ('Acute Coronary Syndrome', 'general-medicine/cardiovascular-medicine/ischemic-heart-disease'),
  ('Cardiac Cycle', 'physiology/cardiovascular-system/heart')
) AS m(topic_key, ref)
WHERE lower(qz."topic_key") = lower(m.topic_key);--> statement-breakpoint

UPDATE "materials" AS mt
SET "curriculum_ref" = m.ref
FROM (VALUES
  ('Acute Inflammation — vascular and cellular events', 'pathology/general-pathology/inflammation'),
  ('Necrosis — patterns and mechanisms', 'pathology/general-pathology/cell-injury-and-adaptation'),
  ('Neoplasia — nomenclature and characteristics', 'pathology/general-pathology/neoplasia'),
  ('Pharmacokinetics — absorption and distribution', 'pharmacology/general-pharmacology/pharmacokinetics'),
  ('Antitubercular Drugs', 'pharmacology/antimicrobial-chemotherapy/antitubercular'),
  ('Brachial Plexus', 'anatomy/upper-limb/pectoral-region-and-axilla'),
  ('ECG — basis and interpretation', 'physiology/cardiovascular-system/heart'),
  ('Mycobacterium tuberculosis', 'microbiology/bacteriology/mycobacteria'),
  ('Acute Coronary Syndrome', 'general-medicine/cardiovascular-medicine/ischemic-heart-disease'),
  ('Cardiac Cycle', 'physiology/cardiovascular-system/heart')
) AS m(topic_key, ref)
WHERE lower(mt."topic_key") = lower(m.topic_key);--> statement-breakpoint

ALTER TABLE "quizzes" DROP COLUMN "topic_key";--> statement-breakpoint
ALTER TABLE "materials" DROP COLUMN "topic_key";--> statement-breakpoint

CREATE INDEX "quizzes_curriculum_ref_idx" ON "quizzes" USING btree ("curriculum_ref");
