/** Realistic content for the development cohort. No lorem ipsum anywhere. */

export { SUBJECTS, type SubjectSlug } from '@/lib/subjects';
export { ROADMAP_TEMPLATES, type RoadmapKey } from '@/lib/roadmap-templates';

import type { RoadmapKey } from '@/lib/roadmap-templates';



/** Behaviour archetype drives how the seeded history is generated. */
export type Archetype =
  | 'exemplary' // near-perfect, long streak
  | 'strong' // consistent with the odd slip
  | 'steady' // reliable but rarely perfect
  | 'improving' // weak start, strong finish
  | 'declining' // strong start, fading
  | 'comeback' // broke a streak, came back hard
  | 'at_risk' // recently missed a couple of days
  | 'struggling'; // needs intervention

export type SeedStudent = {
  fullName: string;
  email: string;
  mbbsYear: number;
  university: string;
  roadmap: RoadmapKey;
  archetype: Archetype;
  dailyMinutes: number;
  goal: string;
  exam?: string;
  obstacle:
    | 'procrastination'
    | 'social_media'
    | 'sleep'
    | 'classes'
    | 'unclear_what_to_study'
    | 'lack_of_motivation'
    | 'personal'
    | 'other';
  baselineDays: number;
  baselineConsistency: number;
  baselineConfidence: number;
};

const UNIS = {
  gmc: 'Government Medical College, Kozhikode',
  jipmer: 'JIPMER, Puducherry',
  kmc: 'Kasturba Medical College, Manipal',
  amc: 'Armed Forces Medical College, Pune',
  mmc: 'Madras Medical College, Chennai',
  bmc: 'Bangalore Medical College',
  gmch: 'Government Medical College, Nagpur',
  smc: 'Seth GS Medical College, Mumbai',
};

export const SEED_STUDENTS: SeedStudent[] = [
  {
    fullName: 'Sara Menon',
    email: 'sara.menon@example.edu',
    mbbsYear: 2,
    university: UNIS.gmc,
    roadmap: 'general_pathology',
    archetype: 'exemplary',
    dailyMinutes: 120,
    goal: 'Finish the whole of General Pathology before the second internal exam.',
    exam: 'Pathology Internal II',
    obstacle: 'social_media',
    baselineDays: 4,
    baselineConsistency: 6,
    baselineConfidence: 3,
  },
  {
    fullName: 'Ahmed Rizvi',
    email: 'ahmed.rizvi@example.edu',
    mbbsYear: 2,
    university: UNIS.jipmer,
    roadmap: 'pharmacology_core',
    archetype: 'strong',
    dailyMinutes: 90,
    goal: 'Complete General Pharmacology and the ANS module with proper notes.',
    exam: 'Pharmacology Sessional',
    obstacle: 'procrastination',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 2,
  },
  {
    fullName: 'Farhana Sheikh',
    email: 'farhana.sheikh@example.edu',
    mbbsYear: 3,
    university: UNIS.kmc,
    roadmap: 'medicine_clinical',
    archetype: 'declining',
    dailyMinutes: 90,
    goal: 'Build a solid clinical approach to chest pain and dyspnoea before postings.',
    exam: 'Medicine Ward Leaving',
    obstacle: 'classes',
    baselineDays: 5,
    baselineConsistency: 7,
    baselineConfidence: 3,
  },
  {
    fullName: 'Imran Qureshi',
    email: 'imran.qureshi@example.edu',
    mbbsYear: 2,
    university: UNIS.gmc,
    roadmap: 'general_pathology',
    archetype: 'steady',
    dailyMinutes: 90,
    goal: 'Get through inflammation and neoplasia without falling behind again.',
    exam: 'Pathology Internal II',
    obstacle: 'procrastination',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
  {
    fullName: 'Divya Nair',
    email: 'divya.nair@example.edu',
    mbbsYear: 1,
    university: UNIS.mmc,
    roadmap: 'anatomy_upper_limb',
    archetype: 'improving',
    dailyMinutes: 75,
    goal: 'Finish upper limb and thorax dissection revision.',
    exam: 'Anatomy Terminal',
    obstacle: 'unclear_what_to_study',
    baselineDays: 1,
    baselineConsistency: 3,
    baselineConfidence: 2,
  },
  {
    fullName: 'Rohit Deshmukh',
    email: 'rohit.deshmukh@example.edu',
    mbbsYear: 1,
    university: UNIS.amc,
    roadmap: 'physiology_core',
    archetype: 'comeback',
    dailyMinutes: 60,
    goal: 'Cover CVS and respiratory physiology properly instead of skimming.',
    obstacle: 'sleep',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
  {
    fullName: 'Aisha Khan',
    email: 'aisha.khan@example.edu',
    mbbsYear: 3,
    university: UNIS.bmc,
    roadmap: 'microbiology_core',
    archetype: 'strong',
    dailyMinutes: 90,
    goal: 'Systematic bacteriology from start to finish, with revision cards.',
    exam: 'Microbiology Prof',
    obstacle: 'lack_of_motivation',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 3,
  },
  {
    fullName: 'Vikram Iyer',
    email: 'vikram.iyer@example.edu',
    mbbsYear: 2,
    university: UNIS.smc,
    roadmap: 'systemic_pathology',
    archetype: 'at_risk',
    dailyMinutes: 90,
    goal: 'Get systemic pathology done before the prof exam.',
    exam: 'Pathology Prof',
    obstacle: 'procrastination',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 3,
  },
  {
    fullName: 'Priya Raghavan',
    email: 'priya.raghavan@example.edu',
    mbbsYear: 4,
    university: UNIS.kmc,
    roadmap: 'obgyn_core',
    archetype: 'exemplary',
    dailyMinutes: 120,
    goal: 'Complete obstetrics and start gynaecology before clinical postings end.',
    exam: 'OBG Prof',
    obstacle: 'classes',
    baselineDays: 5,
    baselineConsistency: 7,
    baselineConfidence: 4,
  },
  {
    fullName: 'Nikhil Varma',
    email: 'nikhil.varma@example.edu',
    mbbsYear: 2,
    university: UNIS.gmch,
    roadmap: 'pharmacology_core',
    archetype: 'struggling',
    dailyMinutes: 60,
    goal: 'Actually start studying pharmacology instead of postponing it.',
    obstacle: 'lack_of_motivation',
    baselineDays: 0,
    baselineConsistency: 2,
    baselineConfidence: 1,
  },
  {
    fullName: 'Meera Pillai',
    email: 'meera.pillai@example.edu',
    mbbsYear: 1,
    university: UNIS.gmc,
    roadmap: 'physiology_core',
    archetype: 'steady',
    dailyMinutes: 75,
    goal: 'Keep up with physiology lectures week by week.',
    obstacle: 'sleep',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 3,
  },
  {
    fullName: 'Arjun Menon',
    email: 'arjun.menon@example.edu',
    mbbsYear: 3,
    university: UNIS.jipmer,
    roadmap: 'medicine_clinical',
    archetype: 'strong',
    dailyMinutes: 105,
    goal: 'Master the common clinical approaches for the ward leaving exam.',
    exam: 'Medicine Ward Leaving',
    obstacle: 'classes',
    baselineDays: 4,
    baselineConsistency: 6,
    baselineConfidence: 3,
  },
  {
    fullName: 'Zoya Ansari',
    email: 'zoya.ansari@example.edu',
    mbbsYear: 2,
    university: UNIS.mmc,
    roadmap: 'general_pathology',
    archetype: 'improving',
    dailyMinutes: 90,
    goal: 'Stop cramming the night before and build a real routine.',
    obstacle: 'procrastination',
    baselineDays: 1,
    baselineConsistency: 3,
    baselineConfidence: 2,
  },
  {
    fullName: 'Karthik Subramanian',
    email: 'karthik.s@example.edu',
    mbbsYear: 4,
    university: UNIS.bmc,
    roadmap: 'medicine_clinical',
    archetype: 'steady',
    dailyMinutes: 90,
    goal: 'Revise medicine systematically alongside internship prep.',
    obstacle: 'personal',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 3,
  },
  {
    fullName: 'Neha Joshi',
    email: 'neha.joshi@example.edu',
    mbbsYear: 1,
    university: UNIS.amc,
    roadmap: 'anatomy_upper_limb',
    archetype: 'strong',
    dailyMinutes: 90,
    goal: 'Finish upper limb before the viva.',
    exam: 'Anatomy Viva',
    obstacle: 'unclear_what_to_study',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
  {
    fullName: 'Sanjay Reddy',
    email: 'sanjay.reddy@example.edu',
    mbbsYear: 2,
    university: UNIS.gmch,
    roadmap: 'systemic_pathology',
    archetype: 'comeback',
    dailyMinutes: 75,
    goal: 'Cover haematology and CVS pathology properly.',
    obstacle: 'social_media',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
  {
    fullName: 'Lakshmi Iyengar',
    email: 'lakshmi.iyengar@example.edu',
    mbbsYear: 3,
    university: UNIS.kmc,
    roadmap: 'microbiology_core',
    archetype: 'exemplary',
    dailyMinutes: 105,
    goal: 'Complete systematic bacteriology and immunology with revision.',
    exam: 'Microbiology Prof',
    obstacle: 'classes',
    baselineDays: 5,
    baselineConsistency: 7,
    baselineConfidence: 3,
  },
  {
    fullName: 'Tanvir Hussain',
    email: 'tanvir.hussain@example.edu',
    mbbsYear: 2,
    university: UNIS.smc,
    roadmap: 'pharmacology_core',
    archetype: 'at_risk',
    dailyMinutes: 60,
    goal: 'Get through the ANS module before the sessional.',
    exam: 'Pharmacology Sessional',
    obstacle: 'sleep',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
  {
    fullName: 'Ananya Bose',
    email: 'ananya.bose@example.edu',
    mbbsYear: 1,
    university: UNIS.mmc,
    roadmap: 'physiology_core',
    archetype: 'improving',
    dailyMinutes: 60,
    goal: 'Build a daily physiology habit from scratch.',
    obstacle: 'lack_of_motivation',
    baselineDays: 0,
    baselineConsistency: 2,
    baselineConfidence: 1,
  },
  {
    fullName: 'Rehan Ali',
    email: 'rehan.ali@example.edu',
    mbbsYear: 3,
    university: UNIS.jipmer,
    roadmap: 'medicine_clinical',
    archetype: 'declining',
    dailyMinutes: 90,
    goal: 'Stay on top of medicine while clinical postings get heavier.',
    obstacle: 'classes',
    baselineDays: 4,
    baselineConsistency: 6,
    baselineConfidence: 3,
  },
  {
    fullName: 'Ishita Kulkarni',
    email: 'ishita.kulkarni@example.edu',
    mbbsYear: 2,
    university: UNIS.bmc,
    roadmap: 'general_pathology',
    archetype: 'strong',
    dailyMinutes: 90,
    goal: 'Complete general pathology with proper diagrams.',
    obstacle: 'procrastination',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 3,
  },
  {
    fullName: 'Deepak Chandra',
    email: 'deepak.chandra@example.edu',
    mbbsYear: 4,
    university: UNIS.gmc,
    roadmap: 'obgyn_core',
    archetype: 'steady',
    dailyMinutes: 75,
    goal: 'Cover obstetrics thoroughly before the prof exam.',
    exam: 'OBG Prof',
    obstacle: 'personal',
    baselineDays: 3,
    baselineConsistency: 5,
    baselineConfidence: 2,
  },
  {
    fullName: 'Nadia Fernandes',
    email: 'nadia.fernandes@example.edu',
    mbbsYear: 1,
    university: UNIS.kmc,
    roadmap: 'anatomy_upper_limb',
    archetype: 'steady',
    dailyMinutes: 75,
    goal: 'Keep pace with dissection and finish thorax.',
    obstacle: 'unclear_what_to_study',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
  {
    fullName: 'Yusuf Ahmed',
    email: 'yusuf.ahmed@example.edu',
    mbbsYear: 2,
    university: UNIS.amc,
    roadmap: 'systemic_pathology',
    archetype: 'struggling',
    dailyMinutes: 60,
    goal: 'Restart pathology after falling badly behind.',
    obstacle: 'personal',
    baselineDays: 0,
    baselineConsistency: 2,
    baselineConfidence: 1,
  },
  {
    fullName: 'Ritika Sharma',
    email: 'ritika.sharma@example.edu',
    mbbsYear: 3,
    university: UNIS.smc,
    roadmap: 'microbiology_core',
    archetype: 'strong',
    dailyMinutes: 90,
    goal: 'Finish bacteriology and start virology.',
    obstacle: 'social_media',
    baselineDays: 3,
    baselineConsistency: 6,
    baselineConfidence: 3,
  },
  {
    fullName: 'Gaurav Malhotra',
    email: 'gaurav.malhotra@example.edu',
    mbbsYear: 2,
    university: UNIS.gmch,
    roadmap: 'pharmacology_core',
    archetype: 'comeback',
    dailyMinutes: 75,
    goal: 'Rebuild the habit after two weeks of nothing.',
    obstacle: 'lack_of_motivation',
    baselineDays: 1,
    baselineConsistency: 3,
    baselineConfidence: 2,
  },
  {
    fullName: 'Shreya Banerjee',
    email: 'shreya.banerjee@example.edu',
    mbbsYear: 4,
    university: UNIS.jipmer,
    roadmap: 'obgyn_core',
    archetype: 'improving',
    dailyMinutes: 90,
    goal: 'Finish obstetrics and get comfortable with labour management.',
    exam: 'OBG Prof',
    obstacle: 'classes',
    baselineDays: 2,
    baselineConsistency: 4,
    baselineConfidence: 2,
  },
];

export const MATERIALS = [
  {
    subject: 'pathology',
    topicKey: 'Acute Inflammation — vascular and cellular events',
    title: 'Acute Inflammation — quick notes',
    type: 'pdf' as const,
    url: 'https://drive.google.com/file/d/example-acute-inflammation-notes/view',
    description: 'Two-page summary of vascular and cellular events with a flow diagram.',
  },
  {
    subject: 'pathology',
    topicKey: 'Acute Inflammation — vascular and cellular events',
    title: 'Robbins Basic Pathology — Chapter 3 reference',
    type: 'textbook' as const,
    url: 'https://www.elsevier.com/books/robbins-basic-pathology/9780323790185',
    description: 'Read pages 57–78 alongside your notes.',
  },
  {
    subject: 'pathology',
    topicKey: 'Necrosis — patterns and mechanisms',
    title: 'Patterns of Necrosis — annotated slides',
    type: 'drive' as const,
    url: 'https://drive.google.com/drive/folders/example-necrosis-slides',
    description: 'Histology slides with the key identifying features marked.',
  },
  {
    subject: 'pathology',
    topicKey: 'Neoplasia — nomenclature and characteristics',
    title: 'Neoplasia nomenclature explained',
    type: 'video' as const,
    url: 'https://www.youtube.com/watch?v=example-neoplasia',
    description: '18-minute walkthrough of benign vs malignant naming.',
  },
  {
    subject: 'pharmacology',
    topicKey: 'Pharmacokinetics — absorption and distribution',
    title: 'ADME in one page',
    type: 'pdf' as const,
    url: 'https://drive.google.com/file/d/example-adme/view',
    description: 'Absorption, distribution, metabolism and excretion on a single sheet.',
  },
  {
    subject: 'pharmacology',
    topicKey: 'Antitubercular Drugs',
    title: 'ATT regimens and side effects',
    type: 'pdf' as const,
    url: 'https://drive.google.com/file/d/example-att/view',
    description: 'RNTCP categories with the classic side-effect table.',
  },
  {
    subject: 'anatomy',
    topicKey: 'Brachial Plexus',
    title: 'Brachial plexus — draw-along video',
    type: 'video' as const,
    url: 'https://www.youtube.com/watch?v=example-brachial-plexus',
    description: 'Learn to draw the plexus from memory in 10 minutes.',
  },
  {
    subject: 'physiology',
    topicKey: 'ECG — basis and interpretation',
    title: 'ECG interpretation — systematic approach',
    type: 'website' as const,
    url: 'https://litfl.com/ecg-library/',
    description: 'The LITFL ECG library — work through the basics section.',
  },
  {
    subject: 'microbiology',
    topicKey: 'Mycobacterium tuberculosis',
    title: 'TB diagnostics summary',
    type: 'pdf' as const,
    url: 'https://drive.google.com/file/d/example-tb-diagnostics/view',
    description: 'Smear, culture, CBNAAT and when to use each.',
  },
  {
    subject: 'general-medicine',
    topicKey: 'Acute Coronary Syndrome',
    title: 'ACS — session recording',
    type: 'recording' as const,
    url: 'https://drive.google.com/file/d/example-acs-recording/view',
    description: 'Recording of the Week 2 guest session on chest pain triage.',
  },
];

export const QUIZ_BANK: {
  subject: string;
  topicKey: string;
  title: string;
  questions: { prompt: string; options: string[]; correctIndex: number; explanation: string }[];
}[] = [
  {
    subject: 'pathology',
    topicKey: 'Acute Inflammation — vascular and cellular events',
    title: 'Acute Inflammation — quick check',
    questions: [
      {
        prompt: 'Which vascular change occurs first in acute inflammation?',
        options: [
          'Transient vasoconstriction',
          'Persistent vasodilatation',
          'Increased permeability',
          'Stasis of blood flow',
        ],
        correctIndex: 0,
        explanation:
          'A brief arteriolar vasoconstriction precedes vasodilatation, which is why the initial blanching is transient.',
      },
      {
        prompt: 'The predominant cell in the first 24 hours of acute inflammation is the:',
        options: ['Lymphocyte', 'Neutrophil', 'Macrophage', 'Eosinophil'],
        correctIndex: 1,
        explanation:
          'Neutrophils dominate the first 24 hours; macrophages take over from roughly 24–48 hours.',
      },
      {
        prompt: 'Which mediator is chiefly responsible for the pain of acute inflammation?',
        options: ['Histamine', 'Bradykinin', 'Leukotriene B4', 'C5a'],
        correctIndex: 1,
        explanation: 'Bradykinin and prostaglandins mediate pain; histamine drives vasodilatation.',
      },
      {
        prompt: 'Margination and rolling of neutrophils is mediated primarily by:',
        options: ['Selectins', 'Integrins', 'Cadherins', 'PECAM-1'],
        correctIndex: 0,
        explanation:
          'Selectins mediate the low-affinity rolling step; integrins mediate firm adhesion.',
      },
      {
        prompt: 'Which of these is a cardinal sign described by Celsus?',
        options: ['Functio laesa', 'Rubor', 'Necrosis', 'Fibrosis'],
        correctIndex: 1,
        explanation:
          'Celsus described rubor, tumor, calor and dolor. Functio laesa was added later by Virchow.',
      },
    ],
  },
  {
    subject: 'pathology',
    topicKey: 'Necrosis — patterns and mechanisms',
    title: 'Necrosis — quick check',
    questions: [
      {
        prompt: 'Coagulative necrosis is characteristic of infarction in every organ EXCEPT the:',
        options: ['Heart', 'Kidney', 'Brain', 'Spleen'],
        correctIndex: 2,
        explanation: 'The brain undergoes liquefactive necrosis due to its high lipid content.',
      },
      {
        prompt: 'Caseous necrosis is classically seen in:',
        options: ['Tuberculosis', 'Acute pancreatitis', 'Gangrene', 'Myocardial infarction'],
        correctIndex: 0,
        explanation: 'Caseous necrosis is the hallmark of tuberculous granulomas.',
      },
      {
        prompt: 'Fat necrosis with saponification is typical of:',
        options: [
          'Acute pancreatitis',
          'Chronic gastritis',
          'Viral hepatitis',
          'Rheumatic fever',
        ],
        correctIndex: 0,
        explanation:
          'Released lipases digest fat; the fatty acids bind calcium to form chalky deposits.',
      },
      {
        prompt: 'Karyorrhexis refers to:',
        options: [
          'Nuclear shrinkage',
          'Nuclear fragmentation',
          'Nuclear fading',
          'Cytoplasmic swelling',
        ],
        correctIndex: 1,
        explanation: 'Pyknosis → karyorrhexis → karyolysis is the sequence of nuclear change.',
      },
      {
        prompt: 'Fibrinoid necrosis is most often associated with:',
        options: ['Immune vasculitis', 'Tuberculosis', 'Ischaemia', 'Bacterial abscess'],
        correctIndex: 0,
        explanation:
          'Immune complexes deposited in vessel walls produce a bright pink fibrin-like appearance.',
      },
    ],
  },
  {
    subject: 'pharmacology',
    topicKey: 'Pharmacokinetics — absorption and distribution',
    title: 'Pharmacokinetics — quick check',
    questions: [
      {
        prompt: 'Bioavailability of an intravenous drug is:',
        options: ['0%', '50%', '100%', 'Variable'],
        correctIndex: 2,
        explanation: 'By definition, IV administration bypasses absorption entirely.',
      },
      {
        prompt: 'First-pass metabolism principally occurs in the:',
        options: ['Kidney', 'Liver', 'Lung', 'Plasma'],
        correctIndex: 1,
        explanation:
          'Orally absorbed drugs traverse the portal circulation and are metabolised hepatically before reaching systemic circulation.',
      },
      {
        prompt: 'A large volume of distribution suggests the drug is:',
        options: [
          'Confined to plasma',
          'Extensively tissue-bound',
          'Highly protein-bound',
          'Rapidly excreted',
        ],
        correctIndex: 1,
        explanation: 'A high Vd implies extensive distribution into tissues rather than plasma.',
      },
      {
        prompt: 'Zero-order kinetics means the rate of elimination is:',
        options: [
          'Proportional to concentration',
          'Constant regardless of concentration',
          'Exponentially rising',
          'Dependent on renal flow only',
        ],
        correctIndex: 1,
        explanation:
          'A fixed amount is eliminated per unit time — as with ethanol, phenytoin at high dose and aspirin.',
      },
      {
        prompt: 'Roughly how many half-lives are needed to reach steady state?',
        options: ['1–2', '4–5', '8–10', '15–20'],
        correctIndex: 1,
        explanation: 'About 4–5 half-lives brings a drug to approximately 94–97% of steady state.',
      },
    ],
  },
  {
    subject: 'physiology',
    topicKey: 'Cardiac Cycle',
    title: 'Cardiac Cycle — quick check',
    questions: [
      {
        prompt: 'The first heart sound corresponds to closure of the:',
        options: [
          'Aortic and pulmonary valves',
          'Mitral and tricuspid valves',
          'Mitral valve only',
          'Pulmonary valve only',
        ],
        correctIndex: 1,
        explanation: 'S1 marks the start of systole as the atrioventricular valves close.',
      },
      {
        prompt: 'Isovolumetric contraction occurs when:',
        options: [
          'All valves are closed and pressure rises',
          'The aortic valve is open',
          'The mitral valve is open',
          'Ventricles are filling',
        ],
        correctIndex: 0,
        explanation:
          'Between AV valve closure and semilunar valve opening, volume is fixed while pressure rises steeply.',
      },
      {
        prompt: 'The "a" wave of the JVP corresponds to:',
        options: [
          'Atrial contraction',
          'Ventricular contraction',
          'Atrial relaxation',
          'Ventricular filling',
        ],
        correctIndex: 0,
        explanation: 'The a wave reflects atrial systole and is absent in atrial fibrillation.',
      },
      {
        prompt: 'Normal ejection fraction is approximately:',
        options: ['25–35%', '40–50%', '55–70%', '80–90%'],
        correctIndex: 2,
        explanation: 'A normal left ventricular ejection fraction is around 55–70%.',
      },
      {
        prompt: 'The dicrotic notch on the aortic pressure curve is caused by:',
        options: [
          'Aortic valve closure',
          'Mitral valve opening',
          'Atrial contraction',
          'Onset of systole',
        ],
        correctIndex: 0,
        explanation:
          'Brief backflow against the closing aortic valve produces the incisura, then a small rebound.',
      },
    ],
  },
];

export const ANNOUNCEMENTS = [
  {
    title: 'Study room moves to 6:00 AM from Monday',
    body: 'We are shifting the morning study room 30 minutes earlier so it does not clash with 7 AM clinical postings. Same link, new time. If mornings genuinely do not work for you, message the group and we will look at an evening slot.',
    isPinned: true,
  },
  {
    title: 'Week 3 focus: stop planning, start finishing',
    body: 'Several of you are planning excellent weeks and completing about half of them. This week, cut your daily target by 20% and finish all five days. A completed 60 minutes beats an abandoned 120.',
    isPinned: false,
  },
];
